### ISSUE TITLE
Nice approach to nested layouts

### ISSUE THREAD

**Issue by trans** [mustache/mustache#138]
I think I just came up with a cool way to support nested layouts without the end-user having to do anything special in view code. Mustache could support layouts in much the same way it supports partials but instead of using `{{>` it would use `{{# ... {{/` style.

Here is an example. Say we have a layout like so:

``` html
<!-- layout.mustache -->
<html>
  <head></head>
  <body>
    {{{yield}}}
  </body>
</html>
```

Then a template:

``` html
<!-- example.mustache -->
{{#> layout}}
    <div id="content">
      <p>Blah blah blah ...</p>
    </div>
{{/ layout}
```

Notice the `>` after the `#`. That's the key. The end result of rendering `example.mustache` would be:

``` html
<!-- example.mustache -->
<!-- layout.mustache -->
<html>
  <head></head>
  <body>
    <div id="content">
      <p>Blah blah blah ...</p>
    </div>
  </body>
</html>
```

I would love to use nested layouts like this, instead of my current approach using `{{> header}} ... {{> footer}}`.

**Comment by deanhiller** [comment]
Did something ever get implemented?  The thing I don't understand above example is that there is ONE variable in the layout 'yield'.....I see most template layouts like playframework / webpieces /etc have multiple locations to tweak such as

`
<html>
  <head>
  {{{title}}}
</head>
  <body>
    {{{activeTab}}}
    {{{yield}}}
  </body>
</html>
`

The 'subtemplate' so to speak needs to provide 3 things here.  I don't see how to do that in one file.  In some frameworks it's a definition like so

{{title}}
  Actual title
{{/title}}
{{activeTab}}
   About Us
{{/activeTab}}
{{yield}}
A huge body of html content here
{{yield}}

Realize I am assuming MULTIPLE layers of extension like in playframework/webpieces so that the overal website has ONE supertemplate and then a logged in user has ONE supertemplate extending the website supertemplate.  Then all logged out pages extend the first supertemplate and all logged in users extend the second supertemplate....seems to work like a charm that way.
